project:
  type: website
  resources:
    - images/

website:
  title: ""

  navbar:
    background: primary
    logo: images/STADS_LOGO_2021_SHORT_wht.png
    left:
      - href: index.qmd
        text: Home
      - href: python/index.qmd
        text: Python Kurs
      - href: vibecoding/index.qmd
        text: Vibe Coding
    right:
      - icon: github
        href: https://github.com/DavidSnr1/stads-quarto-demo

  

format:
  html:
    theme: cosmo
    css: styles/custom.css