project:
  type: website

website:
  title: "Courses"
  sidebar:
    - id: sidebar
      title: "Courses"
      style: "docked"
      contents:
        - python/index.qmd
        - section: "Weeks"
          contents:
            - python/01_basics1.qmd
            - python/02_basics2.qmd
        - vibecoding/index.qmd
        - section: "Weeks"
          contents:
            - vibecoding/01_intro.qmd
            - vibecoding/02_live_coding.qmd
            - vibecoding/03_ai_tools.qmd

format:
  html:
    theme: cosmo
    