name: Deploy Quarto Website

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # NEU: Python installieren
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # NEU: Bibliotheken installieren
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
